### PR TITLE
cli invert axis, add get site all orbitals dos plot

### LINKED ISSUE #142: DosPlotter - new feature request
1. option to add all orbitals for a site to dos plot
2. option to plot invert axis dos

### PR DESCRIPTION
**Pull request by naik-aakash**
Closes #142 

Hi @JaGeo ,

DOS plotting options have been added

1.  `--invertaxis` option can plot DOS now via cli in chemistry conventions
2. Using `--orbital all`  in conjuction with site index for plotting dos, generates a plot with all available orbitals
3. Tests have been updated

### CODE REVIEW

**Comment by naik-aakash** [comment]
Ready for review

**Comment by naik-aakash** [comment]
> Thank you! I have the issue that it always plots the total dos as well. Is this on purpose?

I intentionally kept that. But I can remove this hard coding. I thought it would be nice to always see the total dos when using other options for comparisons

**Comment by JaGeo** [comment]
I don't think it's good. I barely could see the orbital-resolved DOS for some of the test cases

**Comment by naik-aakash** [comment]
> Can we make it optional? Or switch it off?

Sure, we can make it optional . Will make changes tomorrow and let you know when I finish it.

**Comment by naik-aakash** [comment]
Hi @JaGeo, now the dos plotter should not add total dos by default and only adds it when `-- addtotaldos` arg is supplied along with `dos-plot.` However, now the dos-plot always needs to be used with some of the available args like `-- elementdos`, `-- elementspddos`. etc. This will also be made clear in the documentation. 😃

**Review by JaGeo — APPROVED** [review]

**Comment by JaGeo** [comment]
I think it is `--spddos` but this sounds fine as well. It's merged.

**Pull request merged**
