### PR TITLE
rename keys of calc quality summary and snake_case

### LINKED ISSUE #175: calc_quality_summary : dict keys needs to follow snakecase and some renaming
Currently not all keys do not have snake_case convention: got over looked in paper

As lot of things are changed compared to our publication, maybe better to fix them now itself.

Also for example some keys like : charges and bandoverlaps could be renamed to be bit more descriptive as our larger schema already same keys with different data in it on top level 

What do you think @JaGeo ?

### PR DESCRIPTION
**Pull request by naik-aakash**
Closes #175

### CODE REVIEW

**Review by JaGeo — APPROVED** [review]

**Comment by JaGeo** [comment]
@naik-aakash Linting complains.

**Comment by naik-aakash** [comment]
Let me fix the lint issue here so it can be merged

**Comment by naik-aakash** [comment]
> @naik-aakash Linting complains.

Done 😄

**Comment by JaGeo** [comment]
will merge on my way home once the tests pass. Need to enable auto-merge.

**Pull request merged**
