### PR TITLE
Analysis extend + adapt to latest changes in LobterEnv

### LINKED ISSUE #220: Extend Analysis class to work directly with pymatgen objects

### PR DESCRIPTION
**Pull request by naik-aakash**
Closes #220 

# Changes

1.  Adapt Anaylsis class to work with pymatgen objects 
2. Change arg names of LobsterEnv usage to match breaking change

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @JaGeo , What do you think about this changes?

# Open question

Do we want to provide on MP website calc quality description text summary as well? If yes , then I will also adapt that method to work with pymatgen objects

I think only thing left to do would be writing a builder of MP people are able to parse data using our schema.

**Comment by naik-aakash** [comment]
Hi @JaGeo , this PR is could be merged, if no further comments on it 😃

**Review by JaGeo — APPROVED** [review]

**Comment by JaGeo** [comment]
@naik-aakash any chance to increase coverage even further? Otherwise, I will merge

**Comment by naik-aakash** [comment]
> @naik-aakash any chance to increase coverage even further? Otherwise, I will merge

On it, just a sec

**Comment by naik-aakash** [comment]
> > @naik-aakash any chance to increase coverage even further? Otherwise, I will merge
> 
> On it, just a sec

I think this should be it 😄

**Comment by JaGeo** [comment]
Thank you, @naik-aakash !

**Pull request merged**
