### PR TITLE
WIP: Dos plots

### PR DESCRIPTION
**Pull request by davSchnieders**
A naive implementation of a reader for DOSCAR.lobster files. Implements a function to plot DOS directly from the CLI. Connects to #41 

Let me know if something needs changing, I know it is more or less hacked into the CLI, suggestions to make it better are very welcome.

### CODE REVIEW

**Comment by davSchnieders** [comment]
The implementation in pymatgen has a dependency on the VASP POSCAR file, which was not needed for my purposes (and I am using Quantum Espresso anyway...). Hence,. I built my own DOSCAR parser, keeping it agnostic to the electronic structure code.

**Comment by davSchnieders** [comment]
Anyway, I am now realizing that it is missing a way to treat spin-polarized systems, so I will add that in during tomorrows train ride!

**Comment by JaGeo** [comment]
I see. We can certainly fix this directly in pymatgen as well.

**Comment by davSchnieders** [comment]
I can understand your preference to use existing code, especially since LobsterPy already uses pymatgen and also has the POSCAR structure available, so the issues I had with the pymatgen DOSCAR parser do not apply here.

Tests: Yes, for sure, they are missing, as this originated from a small Python script, used solely by myself. I planned to add tests in the course of this pull request. However, since you opt for the pymatgen parser, I will close the pull request instead. In case you change your mind and want to use my parser instead, please let me know, and I will reopen the pull request and add the tests

**Comment by JaGeo** [comment]
I would love to check if we can improve the pymatgen parser based on your implementation!

**Pull request closed without merging**
