### PR TITLE
remove workflow dispactch on push

### PR DESCRIPTION
**Pull request by naik-aakash**
# Change

- Remove doc deployments on push to main branch

### CODE REVIEW

**Comment by JaGeo** [comment]
Why do we want to remove this?

**Comment by naik-aakash** [comment]
> Why do we want to remove this?

Currently it will keep deploying pages on every small change. I feel it's better to have documentation updated only on new version releases. Coz it can happen we merge some PR with new feature and don't release a new version for sometime,then documentation will be updated but pip install won't have that feature

**Comment by JaGeo** [comment]
I would like to keep it as.it is. I have seen issues for other documentations when it was the other way around. We can simply release a new versions frequently.

**Comment by naik-aakash** [comment]
okay

**Pull request closed without merging**
