### PR TITLE
add pre-commit config yaml file

### PR DESCRIPTION
**Pull request by naik-aakash**

### CODE REVIEW

**Comment by naik-aakash** [comment]
> Could you check out this pull request as well? I got stuck somewhere 😅. #91



> Could you check out this pull request as well? I got stuck somewhere 😅. #91

Yes, I will check it out

**Comment by naik-aakash** [comment]
Hi @JaGeo, I checked #91 but do not see any pre-commit config file in that branch. What exactly should I check in there?

**Comment by JaGeo** [comment]
I will merge it. Please try to update the installation process to the latest Python standards as well

**Comment by JaGeo** [comment]
Thanks, @naik-aakash

**Pull request merged**
