### PR TITLE
Update calc quality and fingerprints usage

### LINKED ISSUE #325: Calc quality analysis needs to be updated
After merging this https://github.com/materialsproject/pymatgen/pull/3946 PR and a newer pymatgen release, calc quality analysis needs to be updated

### PR DESCRIPTION
**Pull request by naik-aakash**
Closes #325 

# Changes

1. DosFingerprints usage has been adapted to accommodate latest pymatgen changes
2. pin `pymatgen>=2024.9.10`
3. Remove redundant namedtuple instance of `DosFingerprints` from Lobsterpy (Has been moved to pymatgen in recent changes. See https://github.com/materialsproject/pymatgen/pull/3946)
4. Drop python 3.9 support > pymatgen dropped it in its latest release
5. Fix coverage not being uploaded. (issue : https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes , explicitly ignoring hidden files in uploads)

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @JaGeo, this PR is ready to be merged.

**Review by JaGeo — APPROVED** [review]

**Comment by janosh** [comment]
can we get a new release with these changes for https://github.com/materialsproject/atomate2/pull/990. CI currently failing with

```py
>               fp_lobster_orb = dos_lobster.get_dos_fp(
                    min_e=min_e,
                    max_e=max_e,
                    n_bins=n_bins,
                    normalize=True,
                    type=orb.name,
                )
E               TypeError: CompleteDos.get_dos_fp() got an unexpected keyword argument 'type'
```

**Comment by JaGeo** [comment]
Yes, sure, we can. I thought we had taken care of it already. Sorry

**Comment by JaGeo** [comment]
Should be done, @janosh .

**Comment by janosh** [comment]
pypi still on https://pypi.org/project/lobsterpy/0.4.7. [looks like the publish CI failed due to missing pymatgen release](https://github.com/JaGeo/LobsterPy/actions/runs/11095041804/job/30823193234)

**Comment by JaGeo** [comment]
Yeah. Saw it just now ....

**Comment by JaGeo** [comment]
@janosh done. Release workflow still used Python 3.9... 😉

**Comment by naik-aakash** [comment]
Ops, I somehow overlooked that 😅

**Pull request merged**
