### PR TITLE
Python 3.12 support

### PR DESCRIPTION
**Pull request by JaGeo**

### CODE REVIEW

**Comment by JaGeo** [comment]
@naik-aakash I deactivated flake8 for now. There seems to be an issue with the installation or a bug.
My solution for the Python 3.12 compatibility might not be optimal but should work on Linux at least.

**Comment by naik-aakash** [comment]
> @naik-aakash I deactivated flake8 for now. There seems to be an issue with the installation or a bug. My solution for the Python 3.12 compatibility might not be optimal but should work on Linux at least.

Hi @JaGeo , you mean flake8 fails on python 3.12 ?

**Comment by JaGeo** [comment]
> > @naik-aakash I deactivated flake8 for now. There seems to be an issue with the installation or a bug. My solution for the Python 3.12 compatibility might not be optimal but should work on Linux at least.
> 
> Hi @JaGeo , you mean flake8 fails on python 3.12 ?

Yes, not working. I also cannot fix this very last error. I am not sure if they really drop support for asserting to a Bool?

**Comment by JaGeo** [comment]
@naik-aakash I did it but we have to update "get_lobster_calc_quality_summary" as it raises many warnings.

**Comment by naik-aakash** [comment]
> @naik-aakash I did it but we have to update "get_lobster_calc_quality_summary" as it raises many warnings.

But this is what was expected to raise warnings if certain criteria is not met. Will think of other ways to alert users.  At this time I don't have any other idea to do the same. And that particular test was written to check for all warnings specifically. In actual case, this won't happen

**Pull request merged**
