### PR TITLE
Add units to plotters

### LINKED ISSUE #135: add units to plotters

### PR DESCRIPTION
**Pull request by naik-aakash**
Closes #135 

# Updates

1. Added missing units (eV) to statics and interactive plots when COHP or ICOHP are plotted
2. Update corresponding test and reference test files

`Note:` It would be better to merge this PR before others so that I can resolve merge conflicts arising due to changes in this PR

### CODE REVIEW

**Comment by JaGeo** [comment]
Looks all great:

One thing, the interactive plotter seems to lose it's energy label 

image

**Review by JaGeo — CHANGES_REQUESTED** [review]
I left comments about my outputs. I am not sure why this is happening but this would need to be fixed before I can merge.

Thanks!

**Comment by naik-aakash** [comment]
> lobsterpy automatic-plot-ia --label-resolved

Thanks for spotting this error. I Have fixed the issue now. It was partly a limitation of plotly not being able to render text when added to the latex labels. It should work fine now . Will push the changes in few minutes

**Comment by naik-aakash** [comment]
I hope now it could be merged 😃

**Comment by JaGeo** [comment]
Unfortunately, `lobsterpy automatic-plot-ia --label-resolved` doesn't work anymore... Could you check?

**Comment by JaGeo** [comment]
It also stopped working in the master branch. Not sure why and when.

**Review by JaGeo — APPROVED** [review]

**Pull request merged**
