### PR TITLE
Doscar plotting

### PR DESCRIPTION
**Pull request by naik-aakash**
This PR will implement #41 and close it

- [x] Add a PlainDosPLotter class
- [x] Integrate to cli
- [x] Add tests

### CODE REVIEW

**Comment by naik-aakash** [comment]
Here is the summary of DOS cli args added for getting dos plots. All the plots obtained are non-normalized 

1.` lobsterpy plotdos` # plots only total DOS 
2. `lobsterpy plot-dos --summedspins --spddos` # added spd dos to the plot alongside total DOS and summed-spins arg will sumsup the spin channels
3.` lobsterpy plot-dos  --elementdos`  # adds the element dos alongside total DOS
4.  `lobsterpy plot-dos --summedspins --element K` # addes spd dos for specfied element alongside total dos
5.  `lobsterpy plot-dos --summedspins  --site 1 --orbital 3s` # will add dos for particular orbital as per site index in crystal structure

**Comment by JaGeo** [comment]
Do we have options for smearing as well?

**Comment by naik-aakash** [comment]
> Do we have options for smearing as well?

Yes 😃 we do

**Comment by JaGeo** [comment]
@naik-aakash could you check if we really need the P*TCARs? Please remove them if possible.

**Comment by naik-aakash** [comment]
> @naik-aakash could you check if we really need the P*TCARs? Please remove them if possible.

These POTCARs came from the calc-quality branch as I used that branch as the base to add this extension. I Will try to sort this out

**Comment by JaGeo** [comment]
Thanks, @naik-aakash !

**Comment by naik-aakash** [comment]
Hi @JaGeo , POTCARs have been deleted associated to this PR

**Comment by JaGeo** [comment]
I will merge this soon but it would also be nice to have the chemical DOS in the future as well (energies on the y-axis). I think @kaueltzen implemented this option to pymatgen.

**Comment by JaGeo** [comment]
>  `lobsterpy plot-dos --summedspins --site 1 --orbital 3s` # will add dos for particular orbital as per site index in crystal structure

Is it possible to get all orbitals for one site?

**Comment by naik-aakash** [comment]
> I will merge this soon but it would also be nice to have the chemical DOS in the future as well (energies on the y-axis). I think @kaueltzen implemented this option to pymatgen.

Yes, it is possible to have such dos plots. I did not add in cli yet . Will add this option

**Comment by naik-aakash** [comment]
> > `lobsterpy plot-dos --summedspins --site 1 --orbital 3s` # will add dos for particular orbital as per site index in crystal structure
> 
> Is it possible to get all orbitals for one site?
> 
> And, could you add these options to the documentation? Otherwise, it's hard to discover.

At the moment, no, one can add only one orbital for a site.  But can adapt to make it possible to accept multiple arg. 

Documentation thing I want to take care of this in a separate at-once PR. Cli.py needs to be refactored and I would prefer to do  this once all open PRs are merged and then update documentation or else I feel it will be very repetitive work

**Comment by JaGeo** [comment]
I will merge this as soon as the tests pass and you can add the comments that I made to a new issue and fix them later. I think it's important that we get the feature out.

**Comment by JaGeo** [comment]
Closes #41

**Review by JaGeo — APPROVED** [review]

**Pull request merged**
