### PR TITLE
Bonding antibonding extension

### PR DESCRIPTION
**Pull request by JaGeo**
I am adding another pull request with my suggestions and fixes for the bonding/antibonding extension here.  I think there were some problems with the labels of this function still. We might need to extend the tests to see this.

@naik-aakash : Everything looked okay so far but I think you need to add a test to the analyze part. Please commit your potental changes to this branch when you are back and had time :). 

- Add a test case where you have computed the relevant energy range and where you have an integrated COHP for comparison
- Add a test case without any antibonding states (fully bonding situation)
- Add a test case where you only have antibonding states close to the Fermi level and where you can estimate this percentage from the ICOHPs

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi Janine,

As suggested I made following changes

-  Added test case with zero antibonding interactions in analyze and describe tests
- Changed integration method to trapz because fitting a spline provided unreasonable results

**Comment by JaGeo** [comment]
Thanks! 

Could you add setting an energy range for the integration? Then, you could check only antibonding interactions as well. I am currently not sure if the implementation really works for this case as well.

**Comment by JaGeo** [comment]
@naik-aakash thanks! there is still a conflict that we would need to resolve before merging.

**Comment by naik-aakash** [comment]
Hi @JaGeo ,

I will also update the tests tomorrow morning.

**Comment by naik-aakash** [comment]
Hi @JaGeo,

1. Additional test cases with complete bonding, antibonding and none situations added.
2.  Describe test cases also updated accordingly
3. Additonal condition check added to avoid storing nan values as bonding-antibonding percentages.

**Comment by naik-aakash** [comment]
### CdF2 COHP close to fermi : complete antibonding
CdF2_close_fermi

### CdF2 COHP whole range : bonding antibonding

CdF2_Whole_range

### NaCl COHP whole range : bonding-antibonding case
NaCl_whole_range


### NaCl COHP close to fermi : zero interactions
NaCl_close_fermi

### NaSbF6 whole range: Mixed and complete bonding case
NaSbF6
NaSbF6_Plot

**Comment by JaGeo** [comment]
this looks already very good but as we discussed, the last case indicates a problem with the automatic text generation "no antibonding interaction below Efermi" should be replaced with the percentage.

**Comment by naik-aakash** [comment]
> this looks already very good.
> 
> The following points are open:
> 
> * consistent output in case no antibonding interactions are detected
> * integral of bonding - antibonding should sum up to the absolute value of the ICOHP_sum

Thanks! Will try to find the issue and make outputs consistent.

**Comment by naik-aakash** [comment]
### NaCl COHP whole VASP range : bonding-antibonding case
NaCl_new

### CdF2 COHP whole VASP range : bonding-antibonding case
CdF2_new

### NaSbF6 COHP whole VASP range : bonding-antibonding case
NaSbF6_new
NaSbF6_new_plot

Changes to the code are as follows
1.  consistent output in case no antibonding interactions are detected
2.  Test case added to check (bonding - antibonding ) integrals  == absolute value of the ICOHP_sum with tol of 0.10
3.  Added additional NaCl and CdF test files consisting of computations for whole VASP energy range.

**Comment by JaGeo** [comment]
Looks great :). 

- Only some tests have to be fixed. 
- Maybe add a warning when the results from the integration and the ICOHPs is too far off to alert users that they are not considerin the whole energy range for the COHP computation in Lobster

**Review by JaGeo — COMMENTED** [review]
All fine from my side. I will merge it.

**Pull request merged**
